name: Load Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows you to trigger manually

jobs:
  run-load-test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Load Tests
      run: |
        pytest -m load --junitxml=test-results/load-test-results.xml

    - name: Upload Test Results (Optional)
      uses: actions/upload-artifact@v4
      with:
        name: load-test-results
        path: test-results/load-test-results.xml
